name: "brandOptics AI Code Review - Global Model"

on:
  pull_request:
    types: [opened, synchronize, reopened]
permissions:
  contents: read
  pull-requests: write
  statuses: write

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Run brandOptics AI review
        uses: brandoptics/brandOptics_ai_review_bot_action@v1.1.0
        with:
          openai_key:   ${{ secrets.OPENAI_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}